### ISSUE TITLE
DWIE训练结果求助

### ISSUE THREAD

**Issue by XingYing-stack** [FDUyjx/RSMAN#1]
您好，之前看到您在LogiRE论文的Issue提到，BiLSTM的F1只能到40左右，但您论文中还是引用了LogiRE的数据，请问后来BiLSTM能得到接近50%的结果了么？

**Comment by FDUyjx** [comment]
没，感觉可能还是和数据处理有关

**Comment by XingYing-stack** [comment]
感谢您的回复，祝好。
